export { default as Login } from './Login'
export { default as AppLayout } from './AppLayout'
export { default as Dashboard } from './Dashboard'
export { default as Home } from './Home'
export { default as Patients } from './Patients'
export { default as PatientCreate } from './PatientCreate'